# Generated by Django 5.0.14 on 2025-09-06 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WASTE_BAG',
            },
        ),
        migrations.CreateModel(
            name='BagAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='bag_management.wastebag')),
            ],
            options={
                'db_table': 'BAG_ASSIGNMENT_HISTORY',
            },
        ),
        migrations.CreateModel(
            name='WasteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('organic', 'Organic'), ('glass', 'Glass'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bag_management.bagassignmenthistory')),
            ],
            options={
                'db_table': 'WASTE_PRODUCT',
            },
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
    ]
